### ISSUE TITLE
sekertariat dinas (table tugas dan fungsi , program , struktur (upload file gambar))

### ISSUE THREAD

**Issue by Nanang32** [handyhandoko/gis-kendari-FE#22]

**Comment by Nanang32** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8638821/190937037-e3c4e683-36e5-4302-9839-9fbc204badc6.png">

**Comment by handyhandoko** [comment]
![image](https://user-images.githubusercontent.com/468608/190937856-3164fdf8-0bc4-48e1-a350-05ede813ae39.png)
Bisa jalan di postman, cek variable nya di JS.
