### ISSUE TITLE
Buatkan tombol import di 9 jenis data

### ISSUE THREAD

**Issue by Nanang32** [handyhandoko/gis-kendari-FE#50]
[14:19, 10/29/2022] Luqman fanani mz: io
[14:19, 10/29/2022] Phan: http://127.0.0.1:8000/riverInfrastructures/geoJson

**Comment by handyhandoko** [comment]
Route::get('riverInfrastructures/geoJson', [RiverInfrastructureController::class, 'geoJson']);
Route::get('riverBasins/geoJson', [RiverBasinController::class, 'geoJson']);
Route::get('rivers/geoJson', [RiverController::class, 'geoJson']);
Route::get('watersheds/geoJson', [WatershedController::class, 'geoJson']);
Route::get('weirs/geoJson', [WeirController::class, 'geoJson']);
Route::get('irrigations/geoJson', [IrrigationController::class, 'geoJson']);
Route::get('groins/geoJson', [GroinController::class, 'geoJson']);
Route::get('roads/geoJson', [RoadController::class, 'geoJson']);
Route::get('bridges/geoJson', [BridgeController::class, 'geoJson']);

**Comment by handyhandoko** [comment]
http://127.0.0.1:8000/riverBasins/geoJson
http://127.0.0.1:8000/rivers/geoJson
http://127.0.0.1:8000/watersheds/geoJson
http://127.0.0.1:8000/weirs/geoJson
http://127.0.0.1:8000/irrigations/geoJson
http://127.0.0.1:8000/groins/geoJson
http://127.0.0.1:8000/roads/geoJson
http://127.0.0.1:8000/bridges/geoJson

**Comment by handyhandoko** [comment]
127.0.0.1 ganti jadi base url jgn di hardcode. Karena nanti bisa ganti ip nya kalau sudah upload.

**Comment by handyhandoko** [comment]
https://stackoverflow.com/a/68417576

Bisa pake window.location.origin

**Comment by Nanang32** [comment]
Error 500
- [ ] DAS
- [ ] Sungai
