### ISSUE TITLE
upload image, video, and shp file.

### ISSUE THREAD

**Issue by handyhandoko** [handyhandoko/gis-kendari-FE#63]

**Comment by handyhandoko** [comment]
![image](https://user-images.githubusercontent.com/468608/198823685-daf1a12d-1dd5-4837-b365-06c100f053c5.png)

**Comment by Nanang32** [comment]
untuk data baru mana, 

untuk edit ndak jalan pi

**Comment by Nanang32** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8638821/199384286-210c7e5f-2da6-4346-bd62-ec2d17fd1890.png">
masuk ji gambarnya di db tapi ndak muncul
<img width="430" alt="image" src="https://user-images.githubusercontent.com/8638821/199384354-717d28df-bfc1-4d04-9b95-79f2e858ea81.png">
